---
title: "Demonstration of facilityepimath R package"
author: Damon Toth
institute: University of Utah
format:
  revealjs:
    footer: "Damon Toth"
    self-contained-math: true
    theme: dark
    slide-number: c
---

## Healthcare Facility Transmission {.smaller}

-   Patient-to-patient transmission is important but difficult to document
    -   Inpatient with infection onset may have acquired organism before or after admission
    -   Extent to which transmission-interrupting interventions will reduce infections is unclear
-   **Transmission threshold** effects may be especially important
    -   Can a single high-transmission facility sustain/amplify transmission by itself (within-faciliy $R_0>1$)?
    -   Interventions that reduce $R_0<1$ can be highly impactful and cost-beneficial
-   Mathematical models can help address these topics

## `facilityepimath` R package {.smaller}

-   Provide functions for simulation-free calculations of useful quantities for a differential equation model of healthcare facility transmission

    -   Facility basic reproduction number ($R_0$)

    -   Model equilibrium at a given distribution of admission states

-   Allow flexible user input of heterogenous patient states and length of stay

    -   Heterogeneous susceptibility and transmissibility of states

    -   State-dependent discharge / death rate option

    -   Time-of-stay-dependent dischare/death hazard option

## Differential equation model {.smaller}

General model for two "colonized" compartments $C_1$ and $C_2$ and two "susceptible" compartments $S_1$ and $S_2$

$\frac{dS_1}{dt} = -(s_{21}+(a_{11}+a_{21})\alpha+\omega_1+h(t))S_1 + s{12}S_2 + r_{11}C_1 + r_{12}C_2$

$\frac{dS_2}{dt} = s_{21}S_1 - (s_{12}+(a_{12}+a_{22})\alpha+\omega_2+h(t))S_2 + r_{21}C_1 + r_{22}C_2$

$\frac{dC_1}{dt} = a_{11}\alpha S_1 + a_{12}\alpha S_2 - (c_{21}+r_{11}+r_{21}+\omega_3+h(t))C_1 + c_{12}C_2$

$\frac{dC_2}{dt} = a_{21}\alpha S_1 + a_{22}\alpha S_2 + c_{21}C_1 - (c_{12}+r_{12}+r_{22}+\omega_4+h(t))C_2$

The acquisition rate $\alpha$ in each equation: $\alpha = \beta_1 C_1 + \beta_2 C_2$

Transition rates among the susceptible, colonized states: $s_{ij}$, $c_{ij}$

Colonization clearance rates and $C$-to-$S$ transitions: $r_{ij}$

Relative susceptibility and $S$-to-$C$ transitions: $a_{ij}$

State-dependent removal (death or discharge) rates: $\omega_i$

State-independent, time-of-stay-dependent removal hazard: $h(t)$

## Model components for $R_0$ calculation {.smaller}

::::: columns
::: {.column width="62%"}
Transitions between, and out of, the $S$ states in the absence of colonized patients: $$
S = \left(
\begin{matrix}
    -s_{21}-\omega_1 & s_{12} \\
    s_{21} & -s_{12}-\omega_2
\end{matrix}\right)
$$ Transitions between, and out of, the $C$ states: $$
C = \left(
\begin{matrix}
    -c_{21}-\sum r_{i1}-\omega_3 & c_{12} \\
    c_{21} & -c_{12}-\sum r_{i2}-\omega_4
\end{matrix}\right)
$$ $S$-to-$C$ state transitions when an acquisition occurs: $$
A = \left(
\begin{matrix}
    a_{11} & a_{12} \\
    a_{21} & a_{22}
\end{matrix}\right)
$$
:::

::: {.column width="38%"}
Transmission rates from each colonized compartment: $$
\beta = \left(
\begin{matrix}
    \beta_1 \\
    \beta_2
\end{matrix}\right)
$$ Admission state distribution for susceptible compartments: $$
\theta = \left(
\begin{matrix}
    \theta_1 \\
    \theta_2
\end{matrix}\right)
$$ Moment-generating function associated with $h(t)$: $$ M(t) $$
:::
:::::

## $R_0$ formula {.smaller}

$$
R_0=\frac{\beta^T\int_0^\infty(1-F(t))e^{Ct}\int_0^te^{-C\tau}Ae^{S\tau}\theta\,d\tau\,dt}{1^T\int_0^\infty(1-F(t))e^{St}\theta\,dt}
$$

-    $e^{St}$ and $e^{Ct}$: matrix exponentials

-   $F(t)$: cdf of the distribution with $h(t)$ as the hazard function: $h(t)=\frac{F^\prime(t)}{(1-F(t))}$

    -   If no state-dependent removal ($\omega_i=0$), this is the length of stay distribution

-   Integrals of product of matrix exponential and $(1-F(t))$ can be expressed using the moment-generating function $M(t)$ evaluated at the eigenvalues of the matrix

    -   Formula can generate closed-form solutions when matrix exponentials can be expressed symbolically

    -   We also derived numerical methods to calculate $R_0$ by this formula - encoded in the `facilityR0()` function of our `facilityepimath` R package...
